//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrMelomad.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class empView
    {
        public string fullName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public System.DateTime bDate { get; set; }
        public System.DateTime startDate { get; set; }
        public string roleName { get; set; }
        public string nots { get; set; }
        public byte[] img { get; set; }
        public bool isActive { get; set; }
    }
}
