//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrMelomad.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customersTBL> customersTBL { get; set; }
        public virtual DbSet<productCategoryTBL> productCategoryTBL { get; set; }
        public virtual DbSet<productTBL> productTBL { get; set; }
        public virtual DbSet<suppliersTBL> suppliersTBL { get; set; }
        public virtual DbSet<productView> productView { get; set; }
        public virtual DbSet<empTBL> empTBL { get; set; }
        public virtual DbSet<empView> empView { get; set; }
        public virtual DbSet<roleTBL> roleTBL { get; set; }
        public virtual DbSet<workHoursTBL> workHoursTBL { get; set; }
        public virtual DbSet<orderTBL> orderTBL { get; set; }
        public virtual DbSet<orderView> orderView { get; set; }
    }
}
