//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrMelomad.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class productView
    {
        public string productName { get; set; }
        public string categoryName { get; set; }
        public string nots { get; set; }
        public double productPrice { get; set; }
        public int unitsInStock { get; set; }
        public byte[] img { get; set; }
        public bool isActive { get; set; }
        public int Id { get; set; }
    }
}
