//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrMelomad.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class productTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productTBL()
        {
            this.orderTBL = new HashSet<orderTBL>();
        }
    
        public int Id { get; set; }
        public string productName { get; set; }
        public string nots { get; set; }
        public System.DateTime addDate { get; set; }
        public bool isActive { get; set; }
        public int categoryID { get; set; }
        public byte[] img { get; set; }
        public int unitsInStock { get; set; }
        public double productPrice { get; set; }
    
        public virtual productCategoryTBL productCategoryTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderTBL> orderTBL { get; set; }
    }
}
