//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrMelomad.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class workHoursTBL
    {
        public int Id { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int workerID { get; set; }
        public int currentHourSalary { get; set; }
    
        public virtual empTBL empTBL { get; set; }
    }
}
